### ISSUE TITLE
Pattern support return value

### ISSUE THREAD

**Issue by jenstornell** [getkirby-plugins/patterns-plugin#25]
The function `pattern` echos the pattern directly. In some cases it would be better to have it returned.

**Here is a real example of where it would be good to have return instead of echo:**

```php
<?php e( $template == 'faq', pattern('qa') ); ?>
```

Other than that it could be other things, like the need to filter a pattern. Would be hackish to filter the output string but it's good that it's not impossible.

In snippets you can return the content. Do the same thing here and add it to the docs.

**Comment by jenstornell** [comment]
**Here is from a real live site:**

```php
ob_start();
pattern('image', array(
	'image_url' => $item->image()->toFile()->url(),
	'thumb_url' => thumb( $page->image( $item->image() ), array('width' => $image_size) )->url(),
	'caption' => $item->caption()
));
$out .= ob_get_contents();
ob_end_clean();
```

**Comment by lukasbestle** [comment]
It is already implemented and works exactly the same as the snippet helper:

```
$out = pattern('image', $data, true);
```

**Comment by jenstornell** [comment]
I just downloaded the latest and it's not implemented. It just echos the pattern instead of returning it to pattern.
