### ISSUE TITLE
Preview is blank for patterns in a subfolder

### ISSUE THREAD

**Issue by samnabi** [getkirby-plugins/patterns-plugin#34]
I have created my first two patterns here, a general ad pattern and a banner ad.

For some reason the subfolder pattern (banner) results in a blank preview. Can anyone confirm / offer suggestions to fix this issue?

![screen shot 2016-03-21 at 10 46 05](https://cloud.githubusercontent.com/assets/1731536/13922335/2e3a1180-ef52-11e5-94a5-4d0e95980d64.png)

![screen shot 2016-03-21 at 10 46 13](https://cloud.githubusercontent.com/assets/1731536/13922337/2fd4c314-ef52-11e5-8819-7b639c2d956f.png)

**Comment by jenstornell** [comment]
Write some word in the pattern just to see if it will output anything at all?

If not, look at this issue:

https://github.com/getkirby-plugins/patterns-plugin/issues/16

If it's this issue, you need to view the source to find an error message.

**Comment by samnabi** [comment]
It looks like a cross-browser issue. This problem exists in Firefox and Safari, but Chrome and Opera render the preview just fine.

**Comment by samnabi** [comment]
Firefox dev tools: the `<body>` tag of the `iframe` is empty.

![screen shot 2016-03-21 at 11 04 18](https://cloud.githubusercontent.com/assets/1731536/13922897/b639cb8c-ef54-11e5-9a6f-35c648ecf9ac.png)

Chrome dev tools: the preview is loaded correctly in the `iframe`.
![screen shot 2016-03-21 at 11 05 06](https://cloud.githubusercontent.com/assets/1731536/13922956/f7e6d89a-ef54-11e5-8204-f1cb7e5d45d1.png)

**Comment by samnabi** [comment]
Ah.... silly me. I had adblock on, which was removing the "banner" preview.

Reminder to turn your adblockers off when you design advertisements 😳

**Comment by jenstornell** [comment]
You blocked your self out? :laughing: Sorry, but I just had to laugh a little.
