### ISSUE TITLE
Remove whoops for 2.4.0

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby-plugins/patterns-plugin#41]
The patterns plugin is not compatible with the upcoming 2.4.0 release because of the duplicate whoops debugger.

**Comment by krisak** [comment]
Pretty please?

**Comment by paulrobertlloyd** [comment]
Any closer to being able to resolve this issue…?

**Comment by lukasbestle** [comment]
Sorry for the delay, this is finally fixed. The Patterns plugin should now be compatible with Kirby 2.4.0.

**Comment by krisak** [comment]
@lukasbestle i guess you mean 2.4.1. right? :) 

Thanks a bunch!

**Comment by lukasbestle** [comment]
With 2.4.1 as well. To be precise: The plugin should now be compatible with Kirby 2.4.0+. :)
