### ISSUE TITLE
Possibility to return the pattern's markup instead of directly outputting it

### ISSUE THREAD

**Issue by zvaehn** [getkirby-plugins/patterns-plugin#44]

**Comment by lukasbestle** [comment]
This is already possible with the [third param to the `patterns()` helper](https://github.com/getkirby-plugins/patterns-plugin/blob/507c601d655162c1b60becdaad73f22635262ebc/lib/helpers.php#L3) just like with the Kirby `snippet()` helper.

**Comment by zvaehn** [comment]
Perfect. Sorry about the issue, but i found nothing in the readme about it :(

**Comment by lukasbestle** [comment]
No problem, we should probably document this. :)
