### ISSUE TITLE
[Question] How to extend pattern

### ISSUE THREAD

**Issue by illycz** [getkirby-plugins/patterns-plugin#47]
What is your recommendation if I want extend pattern's nested element by class?

Without structure it's easy:
```
<a class="default-class <?= $class ?>" href="<?= $href ?>"><?= $text ?></a>
<?php pattern('button', array('class' => 'custom-class', 'href' => '#', 'text' => 'Button')) ?>
```
But what if I want extend something like Card component: https://getbootstrap.com/docs/4.0/components/card/ and want different title color for example?

Thanks

**Comment by lukasbestle** [comment]
I'm afraid I don't really understand what you are trying to achieve and how it differs from the simple button example. Could you please explain it some more and/or post a specific markup example?

**Comment by illycz** [comment]
Imagine Tailwind card component like a pattern:

![image](https://user-images.githubusercontent.com/2109984/35684424-1d5ef8a6-0767-11e8-8dd3-256e4f412645.png)

```
<div class="bg-white mx-auto max-w-sm shadow-lg rounded-lg overflow-hidden">
  <div class="sm:flex sm:items-center px-6 py-4">
    <img class="block h-16 sm:h-24 rounded-full mx-auto mb-4 sm:mb-0 sm:mr-4 sm:ml-0" src="https://avatars2.githubusercontent.com/u/4323180?s=400&u=4962a4441fae9fba5f0f86456c6c506a21ffca4f&v=4" alt="">
    <div class="text-center sm:text-left sm:flex-grow">
      <div class="mb-4">
        <p class="text-xl leading-tight">Adam Wathan</p>
        <p class="text-sm leading-tight text-grey-dark">Developer at NothingWorks Inc.</p>
      </div>
      <div>
        <button class="text-xs font-semibold rounded-full px-4 py-1 leading-normal bg-white border border-purple text-purple hover:bg-purple hover:text-white">Message</button>
      </div>
    </div>
  </div>
</div>
```
And display this card without rounded corners, bigger and filled button.

So you need pass many parameters if you need extend all element in pattern.
If you use pattern like molecule (from atomic design) it's impossible change inner atom pattern.

All I'm writing is not a issues, but I'm interested in possible solutions...

Thanks

**Comment by lukasbestle** [comment]
Ah, I see what you mean.

Well, that's always the issue with modular patterns. The more configuration you need, the more options you need to introduce. But of course you don't always need to pass every option to the pattern if you make sure in the pattern snippet that empty variables don't throw warnings.

An alternative is using a [Kirby Brick](https://getkirby.com/docs/toolkit/api/helpers/brick) object instead of writing the HTML by hand. Bricks are much simpler to extend dynamically with configuration objects.

**Comment by illycz** [comment]
@lukasbestle thanks for your time and Kirby Brick reference.
